version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
<<<<<<< HEAD
    target-branch: "main"
    ignore:
      - dependency-name: "de.jflex:jflex"
    groups:
      slf4j:
         patterns:
           - "org.slf4j*"
      junit:
         patterns:
           - "org.junit*"
=======
    target-branch: "develop"
    ignore:
      - dependency-name: "de.jflex:jflex"
>>>>>>> 1746abb1552b81f9bf5540350f9a92e238e90960

  - package-ecosystem: "github-actions"
    # directory of "/" for github-actions means .github/workflows
    directory: "/"
    schedule:
      interval: "weekly"
<<<<<<< HEAD
    target-branch: "main"
=======
    target-branch: "develop"
>>>>>>> 1746abb1552b81f9bf5540350f9a92e238e90960
